// Hand-written frontend domain types (DEVELOPMENT.md §8.1).
// DB row types live in db.ts (generated by `pnpm gen:types`).

export type Role = 'teacher' | 'parent';

// Progressive feature gating (SPEC L16). Core-3 are always on; the rest are opt-in per class.
export type FeatureKey =
  | 'announcements'
  | 'contact'
  | 'messages'
  | 'grades'
  | 'growth'
  | 'calendar'
  | 'leave'
  | 'consent';
export const CORE_FEATURES: FeatureKey[] = ['announcements', 'contact', 'messages'];
export const OPT_IN_FEATURES: FeatureKey[] = [
  'grades',
  'growth',
  'calendar',
  'leave',
  'consent',
];
export type FeatureMap = Record<FeatureKey, boolean>;

export type EventType = 'exam' | 'activity' | 'fee' | 'holiday';
export type LeaveType = 'sick' | 'personal' | 'late';
export type LeaveStatus = 'pending' | 'approved' | 'rejected';
export type PhotoVisibility = 'class' | 'guardians' | 'private';

export interface Profile {
  id: string;
  role: Role;
  displayName: string;
  locale: string;
}

export interface Class {
  id: string;
  name: string;
  officeHours: string;
}

export interface Student {
  id: string;
  classId: string;
  seat: string;
  name: string;
}

export interface Announcement {
  id: string;
  classId: string;
  title: string;
  body: string | null;
  important: boolean;
  publishedAt: string;
  scheduledAt: string | null;
  read?: boolean; // whether the current parent has read it (joined)
  readCount?: number; // teacher-side aggregate
}

export interface HomeworkItem {
  id: string;
  text: string;
  note: string | null;
  dueDate: string;
  done?: boolean;
}

export interface BringItem {
  id: string;
  text: string;
  note: string | null;
  dueDate: string;
}

export interface Exam {
  id: string;
  classId: string;
  name: string;
  published: boolean;
  showDist: boolean;
}

export interface DistBucket {
  range: string;
  lo: number;
  hi: number;
  count: number;
}

export interface GrowthItem {
  kind: 'milestone' | 'grade' | 'note';
  emoji: string;
  title: string;
  desc: string;
  date: string;
}

export interface Photo {
  id: string;
  studentId: string | null;
  caption: string | null;
  storagePath: string;
  visibility: PhotoVisibility;
}

export interface CalendarEvent {
  id: string;
  title: string;
  eventDate: string;
  type: EventType;
}

export interface Leave {
  id: string;
  studentId: string;
  studentName?: string;
  seat?: string;
  leaveDate: string;
  type: LeaveType;
  reason: string | null;
  status: LeaveStatus;
}

export interface ConsentForm {
  id: string;
  title: string;
  deadline: string | null;
}

export interface ConsentStatus {
  signed: Student[];
  unsigned: Student[];
  rate: number;
}

export interface Message {
  id: string;
  conversationId: string;
  senderRole: Role;
  text: string;
  createdAt: string;
}
